stages:
  - deploy

variables:
  NODE_ENV: "production"

before_script:
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa  # Set SSH key
  - chmod 600 ~/.ssh/id_rsa  # Set correct permissions

deploy:
  stage: deploy
  script:
    - npm install -g netlify-cli
    - netlify deploy --prod
  only:
    - main  # or "master" if that's your default branch
