stages:
  - build
  - deploy

variables:
  NODE_ENV: "production"

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build

deploy:
  stage: deploy
  script:
    - npm install -g netlify-cli
    - netlify deploy --prod
  only:
    - main
