[build]
  command = "npm run build"  # Specify the build command for your frontend
  functions = "netlify/functions"  # Path to your serverless functions
  publish = "build"  # Directory to publish (your frontend build)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # This redirect is useful for Single Page Applications (SPAs) to handle client-side routing
  # Uncomment this if you're using a SPA framework like React with React Router

## (optional) Settings for Netlify Dev
[dev]
  command = "npm run start"  # Adjust this based on your local development command
  port = 3000  # Port for the local development server
  publish = "build"  # Folder with the static content for _redirect file

[build.environment]
  # Add your environment variables here, accessible during the build process
  NODE_ENV = "production"
  # Other environment variables...

[context.production.environment]
  # Production environment variables
  REACT_APP_API_BASE_URL = "https://betterment.network"
  REACT_APP_URI=mongodb+srv://jxp100:betterment@cluster0.hhplklu.mongodb.net/Users
JWT_SECRET=r3T!fG^7jPQ2$5hA*9sX&8rZ
CONTACT_PASS=makm rqtr ngou xzig
  # Other production environment variables...
